<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tạo Profile Fb</title>
</head>
<body>
    <?php for($i = 0; $i < 100; $i++) { ?>
        <div>
            <span id="ho<?php echo $i ?>"></span>
            <span id="dem<?php echo $i ?>"></span>
            <span id="ten<?php echo $i ?>"></span>
            <span id="thanh_pho<?php echo $i ?>"></span>
        </div>
    <?php } ?>
</body>
<script>
    var ho = ['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Huỳnh', 'Vũ', 'Võ', 
    'Phan', 'Trương', 'Bùi', 'Đặng', 'Đỗ', 'Ngô', 'Hồ', 'Dương', 'Đinh', ' ']
    var dem = [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'An',
        'Anh',
        'Ánh',
        'Bá',
        'Babie',
        'Bách',
        'BảNh',
        'Bảo',
        'Bắc',
        'Bân',
        'Bdboy',
        'Bích',
        'Bình',
        'Bùi',
        'Cao',
        'Cẩm',
        'Chấn',
        'Châu',
        'Chi',
        'Chí',
        'Chien',
        'Chính',
        'Chuẩn',
        'Chung',
        'Cô',
        'Công',
        'cũ',
        'Cương',
        'Cường',
        'Danh',
        'Diệu',
        'Dình',
        'Dũng',
        'Duy',
        'Dự',
        'Dương',
        'DZ',
        'Đà',
        'Đại',
        'Đạt',
        'Đăng',
        'Đặng',
        'Điêu',
        'Đinh',
        'Đình',
        'Đoàn',
        'Đồng',
        'Đuc',
        'Đức',
        'Em',
        'Gia',
        'Giám',
        'Giang',
        'GiangNguyen',
        'Gucci',
        'Hà',
        'Hàa',
        'Hai',
        'Hài',
        'Hải',
        'Hàn',
        'Hao',
        'Hảo',
        'Hàoo',
        'Hậu',
        'Hi',
        'Hiền',
        'Hiển',
        'Hiến',
        'Hiệp',
        'Hiểu',
        'Hiếu',
        'Hiệu',
        'Hoà',
        'Hòa',
        'Hoài',
        'Hoàn',
        'Hoang',
        'Hoàng',
        'Hong',
        'Hồ',
        'Hồng',
        'Huân',
        'Hung',
        'Hùng',
        'Huu',
        'Huy',
        'Huỳnh',
        'Hưng',
        'Hữu',
        'Jerry',
        'Ken',
        'Khả',
        'Khải',
        'Khang',
        'Khanh',
        'Khánh',
        'Khắc',
        'Khoa',
        'Khuê',
        'Khương',
        'Kien',
        'Kiên',
        'Kiết',
        'Kiều',
        'Kim',
        'Lai',
        'Lam',
        'Lãm',
        'Lạnh',
        'Lâm',
        'Le',
        'Lê',
        'Lễ',
        'Lệ',
        'Lệp',
        'Linh',
        'Long',
        'Lộc',
        'Luân',
        'LUTA',
        'Luu',
        'Lữ',
        'Lương',
        'Lưu',
        'lỳ',
        'Lý',
        'Mai',
        'MaiDiep',
        'Mandista',
        'Manh',
        'Mạnh',
        'Mẫn',
        'Mến',
        'Minh',
        'Mộng',
        'Nam',
        'Nghĩa',
        'Ngọc',
        'Ngốô',
        'Nguyen',
        'Nguyên',
        'Nguyễn',
        'Nhã',
        'Nhan',
        'Nhân',
        'Nhất',
        'Nhật',
        'Nhỏ',
        'Ninh',
        'Phạm',
        'Phan',
        'Phat',
        'Phát',
        'Phi',
        'Phong',
        'Phu',
        'Phú',
        'Phúc',
        'Phùng',
        'Phụng',
        'Phước',
        'Phương',
        'Quách',
        'Quang',
        'Quân',
        'Quốc',
        'Quyền',
        'Quyết',
        'Quỳnh',
        'Ruồi',
        'San',
        'Sang',
        'Sinh',
        'Sói',
        'Sùng',
        'Sử',
        'Sỹ',
        'Tài',
        'Tánh',
        'Tạo',
        'Tâm',
        'Tấn',
        'Thạch',
        'Thái',
        'Thanh',
        'Thành',
        'Thao',
        'Thảo',
        'Thế',
        'Thiên',
        'Thiện',
        'Thiết',
        'Thịnh',
        'Thống',
        'Thơ',
        'Thu',
        'Thuần',
        'Thuấn',
        'Thuận',
        'Thục',
        'Thuỵ',
        'Thúy',
        'thương',
        'Tiền',
        'Tiến',
        'Tinh',
        'Tình',
        'Tính',
        'Tịnh',
        'Toàn',
        'Tòng',
        'Tony',
        'Tố',
        'Tôn',
        'Tới',
        'Tran',
        'Trần',
        'Trí',
        'Triều',
        'Trong',
        'Trọng',
        'Trung',
        'Truong',
        'Truòng',
        'Trương',
        'Trường',
        'Tu',
        'Tú',
        'Tuan',
        'Tuân',
        'Tuấn',
        'Tùng',
        'Tuyên',
        'Tường',
        'Văn',
        'Vân',
        'Vĩ',
        'Việt',
        'Vĩnh',
        'Võ',
        'Vũ',
        'Vương',
        'Vy',
        'Xịn',
        'Xuân',
        'Xuyên',
        'Xương',
    ]

    var ten = [
        'Long',
        'Thành',
        'Lý',
        'Thịnh',
        'Thảo',
        'Minh',
        'Sa',
        'Dayy',
        'Phát',
        'Khải',
        'Trực',
        'Bảo',
        'Đạt',
        'Thạch',
        'Vỹ',
        'Tran',
        'Tùng',
        'Quân',
        'Mạnh',
        'Cường',
        'Phạm',
        'Đại',
        'Khánh',
        'Anh',
        'Chí',
        'Danh',
        'Luân',
        'Lê',
        'Giàu',
        'Tuyên',
        'Văn',
        'Hoài',
        'Nhân',
        'Ngáoo',
        'Ca',
        'Hạnh',
        'Tâm',
        'Đông',
        'Tuấn',
        'Tiến',
        'Thanh',
        'Dương',
        'Bình',
        'Hiển',
        'Hào',
        'Cuong',
        'KBân',
        'Hieu',
        'Bâng',
        'Nguyễn',
        'Lâm',
        'Liêm',
        'Kiệt',
        'Phúc',
        'Thuyết',
        'Miên',
        'Hiếu',
        'Dũng',
        'Khanh',
        'Bách',
        'Giang',
        'Nam',
        'Tỉnh',
        'Đức',
        'Tưởng',
        'Đô',
        'Hảo',
        'An',
        'Quách',
        'Lực',
        'Ngữ',
        'Thuận',
        'Tú',
        'Chung',
        'Phương',
        'Huy',
        'Thương',
        'Kiên',
        'Châu',
        'Duy',
        'Võ',
        'Lệp',
        'Trung',
        'Vinh',
        'Nghĩa',
        'Hải',
        'Khoa',
        'Quỳnh',
        'Trường',
        'Chinh',
        'Hòa',
        'Lợi',
        'Đa',
        'Lăng',
        'Điền',
        'Bùi',
        'Hoàng',
        'Hợp',
        'Thọ',
        'Triển',
        'Nghiệp',
        'Tiền',
        'Vi',
        'Tăng',
        'Phong',
        'Hoa',
        'Sinh',
        'Hậu',
        'Phi',
        'Thưởng',
        'Đàm',
        'Binh',
        'Linh',
        'Chuẩn',
        'Nhật',
        'Giao',
        'Liệu',
        'Sơn',
        'Khang',
        'Quý',
        'Chính',
        'Thái',
        'Mai',
        'Doanh',
        'Việt',
        'Trần',
        'Quang',
        'Nguyên',
        'Hưng',
        'Chương',
        'Dân',
        'Ngon',
        'Bang',
        'Dat',
        'Van',
        'Hung',
        'Dang',
        'Thang',
        'Bắc',
        'Phước',
        'My',
        'Trang',
        'Almira',
        'La',
        'Kha',
        'Tương',
        'Tụng',
        'Ly',
        'Hoang',
        'Chau',
        'Vu',
        'Hùng',
        'Vo',
        'Phùng',
        'Chu',
        'Tố',
        'Do',
        'Mỹ',
        'Ba',
        'Thiện',
        'Trương',
        'Dao',
        'Phan',
        'Bao',
        'Hai',
        'Điển',
        'Hà',
        'Khẩn',
        'Đinh',
        'Nhất',
        'Huynh',
        'Tài',
        'Tiếp',
        'Khểnh',
        'Trọng',
        'Gia',
        'Lân',
        'Thông',
        'Luu',
        'Ðiệp',
        'Hiệp',
        'Đoàn',
        'Toàn',
        'Bằng',
        'Triết',
        'Cương',
        'Hữu',
        'Hường',
        'Ân',
        'Thắng',
        'Nga',
        'Vân',
        'Quyên',
        'Chi',
        'Tường',
        'Tân',
        'Hiền',
        'Tín',
        'Ngô',
        'Đan',
        'Lộc',
        'Kiện',
        'Vượng',
        'Quan',
    ]
    const tinh = [
        'An Giang',
        'Vũng Tàu',
        'Bạc Liêu',
        'Bắc Giang',
        'Bắc Kạn',
        'Bắc Ninh',
        'Bến Tre',
        'Bình Dương',
        'Bình Định',
        'Bình Phước',
        'Bình Thuận',
        'Cà Mau',
        'Cao Bằng',
        'Cần Thơ',
        'Đà Nẵng',
        'Đắk Lắk',
        'Đắk Nông',
        'Điện Biên',
        'Đồng Nai',
        'Đồng Tháp',
        'Gia Lai',
        'Hà Giang',
        'Hà Nam',
        'Hà Nội',
        'Hà Tĩnh',
        'Hải Dương',
        'Hải Phòng',
        'Hậu Giang',
        'Hòa Bình',
        'Hưng Yên',
        'Khánh Hòa',
        'Kiên Giang',
        'Kon Tum',
        'Lai Châu',
        'Lạng Sơn',
        'Lào Cai',
        'Lâm Đồng',
        'Long An',
        'Nam Định',
        'Nghệ An',
        'Ninh Bình',
        'Ninh Thuận',
        'Phú Thọ',
        'Phú Yên',
        'Quảng Bình',
        'Quảng Nam',
        'Quảng Ngãi',
        'Quảng Ninh',
        'Quảng Trị',
        'Sóc Trăng',
        'Sơn La',
        'Tây Ninh',
        'Thái Bình',
        'Thái Nguyên',
        'Thanh Hóa',
        'Thừa Thiên Huế',
        'Tiền Giang',
        'Tp Hồ Chí Minh',
        'Trà Vinh',
        'Tuyên Quang',
        'Vĩnh Phúc',
        'Yên Bái',
    ]

</script>
<script>
    function getRandomNumber(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }
    for(let i = 0; i < 100; i++) {
        const ho_output =document.querySelector(`#ho${i}`)
        ho_output.textContent = ho[getRandomNumber(0, 16)]
        
        const dem_output = document.querySelector(`#dem${i}`)
        dem_output.textContent = dem[getRandomNumber(0, 277)]

        const ten_output = document.querySelector(`#ten${i}`)
        ten_output.textContent = ten[getRandomNumber(0, 203)]
    }
</script>
</html>